'use strict';
const C=CandyCore, KEY='pokesleep-candy-v1', $=id=>document.getElementById(id);
const methods={help:'おてつだい',mew:'ミュウ',delibird:'デリバード'},names=Object.keys(candyMap);
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2);
const clone=x=>JSON.parse(JSON.stringify(x)), el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const label=p=>p.nickname||p.species, position=n=>n===1?'1 リーダー':String(n);
const fresh=()=>({version:2,pokemon:[],team:[null,null,null,null,null],records:[],events:[],settings:{mew:true,delibird:true}});
let state=fresh(),blocked=false,selected='',eventId=null,activeTab='record',actors={mew:'',delibird:''};
function notice(s){$('notice').textContent=s;}
function load(){try{const raw=localStorage.getItem(KEY);if(raw){const old=JSON.parse(raw);state=C.migrate(old,candyMap);if(old.version===1){localStorage.setItem(KEY+'-before-v2',raw);localStorage.setItem(KEY,JSON.stringify(state));}}else{for(let i=0;i<5;i++){const species=localStorage.getItem('pokemon-slot-'+i);if(names.includes(species)){const p={id:uid(),species,nickname:'',profile:null};state.pokemon.push(p);state.team[i]=p.id;}}localStorage.setItem(KEY,JSON.stringify(state));}}catch(e){blocked=true;notice('保存データを読み込めません。上書きを停止しました。設定からバックアップを書き出してください。');}}
// 履歴と編成をまとめて保存。保存できた時だけ画面の状態を確定します。
function commit(next,message){if(blocked){notice('保存を停止しています。設定からバックアップの復元が必要です。');return false;}try{const checked=C.migrate(next,candyMap);localStorage.setItem(KEY,JSON.stringify(checked));state=checked;render();notice(message);return true;}catch(e){notice('保存できませんでした：'+e.message);return false;}}
function button(text,action,cls){const b=el('button',text,cls);b.type='button';b.onclick=action;return b;}
function row(parent,name,value,cls){const r=el('div',undefined,'row '+(cls||''));r.append(el('span',name),el('strong',value));parent.append(r);}
function optionList(select,items,value,empty='選択してください'){select.replaceChildren(new Option(empty,''));for(const item of items)select.add(new Option(item.text,item.id));select.value=value||'';}
function currentTeam(){return state.team.map(id=>state.pokemon.find(p=>p.id===id)||null);}
function recordDate(){return $('auto-now').checked?new Date():C.fromInput($('datetime').value);}
function skillContext(method){const team=currentTeam(),actorIndex=team.findIndex(p=>p&&p.id===actors[method]);const p=team[actorIndex];const date=recordDate();if(!p||!p.profile||!Number.isFinite(date.getTime()))return null;const event=C.eventFor(state.events,C.gameDay(date),method);return {team:clone(team),actorId:p.id,actorSlot:actorIndex+1,event,effectiveLevel:Math.min(8,p.profile.skillLevel+event.boost)};}
function record(method,slot,amount){const date=recordDate();if(!Number.isFinite(date.getTime())){notice('記録日時を入力してください。');return;}const team=currentTeam(),p=team[slot-1],skillOnly=method==='delibird'&&slot===6;const context=method==='help'?{team:clone(team),actorId:null,actorSlot:null,event:null,effectiveLevel:null}:skillContext(method);
 if((!p&&!skillOnly)||!context){notice('編成と発動個体の個体情報を設定してください。');return;}
 if(method==='mew'&&!C.mewAmounts(context.effectiveLevel).includes(amount)){renderRecord();notice('日時に対応するスキルレベルでボタンを更新しました。もう一度選んでください。');return;}
 if($('auto-now').checked)$('datetime').value=C.localInput(date);
 const r={id:uid(),datetime:date.toISOString(),method,amount,slot,pokemonId:skillOnly?null:p.id,pokemon:skillOnly?'スキル発動のみ':label(p),species:skillOnly?null:p.species,nickname:skillOnly?'':p.nickname,candy:skillOnly?null:candyMap[p.species],context};
 commit({...state,records:[...state.records,r]},`${methods[method]}：${skillOnly?'スキル発動のみ（アメなし）':position(slot)+'・'+r.candy+' '+amount+'個'}を記録しました。`);
}
function totals(parent,records,title){parent.replaceChildren(el('small',title),el('div',`${C.sum(records)}個`,'total'));for(const [method,name] of Object.entries(methods)){const rs=records.filter(r=>r.method===method);row(parent,name,`${C.sum(rs)}個${method==='help'?'':` · 発動${rs.length}回`}`,method);} }
function renderRecord(){
 totals($('today-total'),state.records.filter(r=>C.gameDay(r.datetime)===C.gameDay(new Date())),`今日 ${C.gameDay(new Date())}（朝4時〜）`);
 const root=$('record-methods');root.replaceChildren();const team=currentTeam();
 for(const [method,name] of Object.entries(methods)){
  if(method!=='help'&&!state.settings[method])continue;
  const section=el('div',undefined,method);section.id=method+'-section';section.append(el('h2',name));let context=null;
  if(method!=='help'){
   const candidates=team.map((p,i)=>p&&p.species===name?{id:p.id,text:`${position(i+1)} · ${label(p)}`} : null).filter(Boolean);
   if(!candidates.some(p=>p.id===actors[method]))actors[method]=candidates.length===1?candidates[0].id:'';
   const l=el('label','発動した個体'),s=el('select');s.id=method+'-actor';optionList(s,candidates,actors[method]);s.onchange=()=>{actors[method]=s.value;renderRecord();};l.append(s);section.append(l);
   context=skillContext(method);
   if(!context){section.append(el('p',candidates.length?'発動個体を選び、設定で個体情報を保存してください。':'編成に'+name+'を入れると記録できます。','muted'));}
   else{section.append(el('p',`スキルLv.${context.effectiveLevel} · 確率${context.event.multiplier}倍 · ${context.event.name}`,'muted'));}
  }
  const grid=el('div',undefined,'record-slots');grid.id=method+'-slots';
  team.forEach((p,i)=>{
   const box=el(method==='mew'?'div':'button',undefined,'help-card');box.append(el('small',position(i+1)),el('strong',p?(method==='help'?label(p):candyMap[p.species]):'未設定'));
   if(method==='mew'){const actions=el('div',undefined,'mew-actions');for(const amount of context?C.mewAmounts(context.effectiveLevel):[1]){const b=button(amount+'個',()=>record(method,i+1,amount));b.disabled=!p||!context;actions.append(b);}box.append(actions);}
   else{box.type='button';box.disabled=!p||(method!=='help'&&!context);box.onclick=()=>record(method,i+1,method==='help'?2:4);}
   grid.append(box);
  });
  if(method==='delibird'){const b=button('',()=>record('delibird',6,0),'help-card');b.append(el('small','6 · アメなし'),el('strong','スキル発動のみ'));b.disabled=!context;grid.append(b);}
  section.append(grid);root.append(section);
 }
}
function historicalActors(method){const species=methods[method],map=new Map();for(const p of state.pokemon)if(p.species===species)map.set(p.id,label(p));for(const r of state.records)if(r.method===method&&r.context?.actorId){const p=r.context.team[r.context.actorSlot-1];if(!map.has(p.id))map.set(p.id,label(p)+'（登録解除済み）');}return [...map].map(([id,text],i)=>({id,text:`${text} · 個体${i+1}`}));}
function renderActorFilters(){const s=$('summary-actor');optionList(s,[...historicalActors('delibird'),{id:'unknown',text:'発動個体不明（以前の記録）'}],s.value,'全個体');const a=$('analysis-actor');optionList(a,historicalActors($('analysis-method').value),a.value,'全個体');}
function filteredRecords(){const period=C.range($('period').value,$('summary-date').value||C.gameDay(new Date())),actor=$('summary-actor').value;return state.records.filter(r=>C.inRange(r,period)&&(r.method!=='delibird'||!actor||(actor==='unknown'?!r.context?.actorId:r.context?.actorId===actor)));}
function calendar(parent,month,cell){parent.replaceChildren();if(!/^\d{4}-\d{2}$/.test(month))return;for(const d of ['月','火','水','木','金','土','日'])parent.append(el('span',d,'weekday'));const first=month+'-01',offset=(new Date(first).getUTCDay()+6)%7;for(let i=0;i<offset;i++)parent.append(el('span'));for(let day=first;day.startsWith(month);day=C.addDays(day,1)){const date=day;parent.append(cell(date));}}
function renderSummary(){
 const rs=filteredRecords(),period=C.range($('period').value,$('summary-date').value||C.gameDay(new Date()));$('range-label').textContent=period?`${period[0]} 朝4時 〜 ${period[1]} 朝4時`:'全期間';totals($('summary-total'),rs,'選択期間のアメ');
 const actor=$('summary-actor').value;const calendarRs=state.records.filter(r=>r.method!=='delibird'||!actor||(actor==='unknown'?!r.context?.actorId:r.context?.actorId===actor));
 calendar($('candy-calendar'),$('candy-month').value,date=>{const b=button('',()=>{$('summary-date').value=date;$('period').value='day';renderSummary();},'day');b.append(el('small',Number(date.slice(-2))));for(const method of Object.keys(methods)){const total=C.sum(calendarRs.filter(r=>r.method===method&&C.gameDay(r.datetime)===date));b.append(el('span',String(total),method));}b.setAttribute('aria-label',date+'のアメ');if(date===$('summary-date').value)b.classList.add('selected');return b;});
 $('slot-counts').replaceChildren();for(const [method,name] of Object.entries(methods)){const group=el('div',undefined,method);const source=rs.filter(r=>r.method===method);group.append(el('h4',`${name}${method==='help'?'':` · 発動${source.length}回`}`));for(let i=1;i<=5;i++){const xs=source.filter(r=>r.slot===i);row(group,position(i),`${xs.length}回 · ${C.sum(xs)}個`);}if(method==='delibird')row(group,'6 · スキル発動のみ',source.filter(r=>r.slot===6).length+'回');const unknown=source.filter(r=>r.slot===null);if(unknown.length)row(group,'獲得位置不明',unknown.length+'回 · '+C.sum(unknown)+'個');$('slot-counts').append(group);}
 $('candy-list').replaceChildren();const candies={};for(const r of rs)if(r.candy&&r.amount)candies[r.candy]=(candies[r.candy]||0)+r.amount;for(const [c,n] of Object.entries(candies).sort((a,b)=>b[1]-a[1]))row($('candy-list'),c,n+'個');if(!Object.keys(candies).length)$('candy-list').append(el('p','まだアメの記録がありません。'));
 renderAnalysis(rs);
}
function renderAnalysis(records){
 const method=$('analysis-method').value,actor=$('analysis-actor').value,level=$('analysis-level').value,multi=$('analysis-multiplier').value,amount=$('analysis-amount').value;
 const source=records.filter(r=>r.method===method),unknown=source.filter(r=>!r.context?.actorId||!r.slot).length;
 const rs=source.filter(r=>r.context?.actorId&&r.slot&&(!actor||r.context.actorId===actor)&&(!level||r.context.effectiveLevel===Number(level))&&(!multi||r.context.event.multiplier===Number(multi))&&(amount===''||r.amount===Number(amount)));
 const root=$('analysis');root.className=method;root.replaceChildren(el('p',`分析対象 ${rs.length}回 · 位置などが不明な記録 ${unknown}回は除外`));
 const wrap=el('div',undefined,'table-scroll'),table=el('table'),head=el('tr');head.append(el('th','発動位置 ↓／獲得先 →'));for(let i=1;i<=(method==='mew'?5:6);i++)head.append(el('th',i===6?'アメなし':String(i)));head.append(el('th','発動回数'));table.append(head);
 for(let i=1;i<=5;i++){const tr=el('tr'),xs=rs.filter(r=>r.context.actorSlot===i);tr.append(el('th',position(i)));for(let j=1;j<=(method==='mew'?5:6);j++){const count=xs.filter(r=>r.slot===j).length;tr.append(el('td',`${count}回\n${xs.length?(count/xs.length*100).toFixed(1)+'%':'—'}`));}tr.append(el('td',xs.length+'回'));table.append(tr);}wrap.append(table);root.append(wrap);
 for(const count of method==='mew'?[1,2,3,4]:[0,4])row(root,`${count}個の記録`,rs.filter(r=>r.amount===count).length+'回');
 if(rs.length<30)root.append(el('p','記録が少ない間は割合が大きく変わります。件数と一緒に確認してください。','muted'));
}
function oldLabel(r){if(r.amount===0)return 'スキル発動のみ';if(typeof r.nickname==='string')return r.nickname||r.species;return r.pokemon.replace(/ · #[a-zA-Z0-9-]+$/,'').replace('（'+r.species+'）','');}
function profileText(p){if(!p.profile)return '個体情報不明';const v=p.profile;return `Lv.${v.level} · ${v.nature} · スキルLv.${v.skillLevel}\n`+v.subskills.map((s,i)=>`${[10,25,50,75,100][i]}: ${s||'未入力'}${v.level<[10,25,50,75,100][i]?'（未解放）':''}`).join(' / ');}
function renderHistory(){const root=$('history-list');root.replaceChildren();for(const r of [...state.records].reverse().sort((a,b)=>Date.parse(b.datetime)-Date.parse(a.datetime))){const card=el('div',undefined,'card '+r.method);card.append(el('strong',`${methods[r.method]} · ${r.amount}個`),el('p',`${C.localInput(r.datetime).replace('T',' ')}（日本時間）\n${r.slot===6?'アメなし':r.slot?position(r.slot):'獲得位置不明'} · ${r.candy||'スキル発動のみ'}\n${oldLabel(r)}`));const details=el('details'),summary=el('summary','発動時の編成・個体・補正');details.append(summary);
 if(!r.context){details.append(el('p','以前の記録のため、当時の編成・発動個体・補正は不明です。'));}
 else{const c=r.context;if(r.method!=='help'){const p=c.team[c.actorSlot-1];details.append(el('p',`発動：${position(c.actorSlot)} · ${label(p)}\n補正後スキルLv.${c.effectiveLevel} · 確率${c.event.multiplier}倍 · レベル+${c.event.boost} · ${c.event.name}`));}c.team.forEach((p,i)=>details.append(el('p',`${position(i+1)} · ${p?label(p)+'（'+p.species+'）':'未設定'}\n${p?profileText(p):''}`)));}card.append(details,button('この記録を削除',()=>{if(confirm('この記録を削除しますか？ 集計にも反映されます。'))commit({...state,records:state.records.filter(x=>x.id!==r.id)},'記録を削除しました。');},'danger'));root.append(card);}if(!state.records.length)root.append(el('p','まだ記録がありません。'));}
function renderTeam(){const root=$('team-slots');root.replaceChildren();state.team.forEach((id,i)=>{const l=el('label',position(i+1)),s=el('select');s.setAttribute('aria-label',position(i+1));optionList(s,state.pokemon.map((p,n)=>({id:p.id,text:`${label(p)}${state.pokemon.filter(x=>label(x)===label(p)).length>1?' · 個体'+(n+1):''}`})),id,'未設定');for(const o of s.options)if(o.value&&state.team.some((pid,j)=>j!==i&&pid===o.value))o.disabled=true;s.onchange=()=>{const team=[...state.team];team[i]=s.value||null;commit({...state,team},'編成を保存しました。');};l.append(s);root.append(l);});const list=$('registered-pokemon-list');list.replaceChildren();for(const p of state.pokemon){const card=el('div',undefined,'card '+(p.species==='ミュウ'?'mew':p.species==='デリバード'?'delibird':''));card.append(el('strong',label(p)),el('p',candyMap[p.species]+' · '+(p.profile?'個体情報登録済み':'個体情報未設定')),button('編集',()=>{showTab('settings');$('profile-select').value=p.id;editProfile();}),button('登録解除',()=>{if(confirm(label(p)+'を登録解除しますか？ 過去の履歴は残ります。'))commit({...state,pokemon:state.pokemon.filter(x=>x.id!==p.id),team:state.team.map(id=>id===p.id?null:id)},'登録解除しました。');},'danger'));list.append(card);}}
function normalize(s){return s.normalize('NFKC').trim().replace(/[\u3041-\u3096]/g,c=>String.fromCharCode(c.charCodeAt(0)+96));}
function renderCatalog(){const q=normalize($('pokemon-search').value),root=$('pokemon-search-results');root.replaceChildren();for(const name of names.filter(n=>normalize(n).includes(q)))root.append(button(name,()=>{selected=name;$('selected-name').textContent=name;$('add-pokemon').disabled=false;}));if(!root.children.length)root.append(el('p','該当するポケモンがありません。'));}
const natures='がんばりや さみしがり ゆうかん いじっぱり やんちゃ ずぶとい すなお のんき わんぱく のうてんき おくびょう せっかち まじめ ようき むじゃき ひかえめ おっとり れいせい てれや うっかりや おだやか おとなしい なまいき しんちょう きまぐれ'.split(' ');
const subskills='きのみの数S おてつだいボーナス スキルレベルアップS スキルレベルアップM スキル確率アップS スキル確率アップM おてつだいスピードS おてつだいスピードM 食材確率アップS 食材確率アップM 最大所持数アップS 最大所持数アップM 最大所持数アップL げんき回復ボーナス 睡眠EXPボーナス リサーチEXPボーナス ゆめのかけらボーナス'.split(' ');
function editProfile(){const p=state.pokemon.find(p=>p.id===$('profile-select').value);$('profile-form').hidden=!p;if(!p)return;const v=p.profile||C.profileDefault(p.species);$('profile-species').textContent=p.species;$('profile-form').className=p.species==='ミュウ'?'mew':p.species==='デリバード'?'delibird':'';$('profile-nickname').value=p.nickname;$('profile-level').value=v.level;$('profile-nature').value=p.species==='ミュウ'?'きまぐれ':v.nature;$('profile-nature').disabled=p.species==='ミュウ';$('profile-skill').value=v.skillLevel;v.subskills.forEach((s,i)=>$('subskill-'+i).value=s);}
function renderSettings(){ $('enable-mew').checked=state.settings.mew;$('enable-delibird').checked=state.settings.delibird;const p=$('profile-select'),old=p.value;optionList(p,state.pokemon.map((p,i)=>({id:p.id,text:`${label(p)} · 個体${i+1}`})),old);editProfile();renderEvents();}
function selectEvent(e){eventId=e?.id||null;$('event-name').value=e?.name||'';$('event-start').value=e?.start||C.range('week',C.gameDay(new Date()))[0];$('event-end').value=e?.end||C.addDays(C.range('week',C.gameDay(new Date()))[1],-1);$('event-target').value=e?.target||'both';$('event-multiplier').value=e?.multiplier||1;$('event-boost').value=e?.boost||0;$('cancel-event').hidden=!e;}
function renderEvents(){calendar($('event-calendar'),$('event-month').value,date=>{const es=state.events.filter(e=>e.start<=date&&e.end>=date);const b=button('',()=>{selectEvent(null);const range=C.range('week',date);$('event-start').value=range[0];$('event-end').value=C.addDays(range[1],-1);},'day');b.append(el('small',Number(date.slice(-2))));for(const e of es)b.append(el('span',e.multiplier+'× / +'+e.boost,e.target==='both'?'':e.target));if(es.length)b.classList.add('event-day');b.setAttribute('aria-label',date+'のイベント設定');return b;});const root=$('event-list');root.replaceChildren();for(const e of [...state.events].sort((a,b)=>a.start.localeCompare(b.start))){const box=el('div',undefined,e.target==='both'?'':e.target);box.append(el('p',`${e.name} · ${e.start}〜${e.end}\n${e.target==='both'?'ミュウ・デリバード':methods[e.target]} · 確率${e.multiplier}倍 · スキルレベル+${e.boost}`),button('編集',()=>selectEvent(e)),button('削除',()=>{if(confirm('このイベント設定を削除しますか？ 記録済みの履歴は変更されません。')){if(commit({...state,events:state.events.filter(x=>x.id!==e.id)},'イベント設定を削除しました。'))selectEvent(null);}},'danger'));root.append(box);}}
function showTab(id){activeTab=id;for(const name of ['record','summary','history','team','settings'])$(name).hidden=name!==id;for(const b of document.querySelectorAll('[data-tab]')){if(b.dataset.tab===id)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}if(id==='record')renderRecord();if(id==='summary')renderSummary();window.scrollTo({top:0});}
function render(){renderRecord();renderActorFilters();renderSummary();renderHistory();renderTeam();renderSettings();}
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>showTab(b.dataset.tab);
$('datetime').oninput=()=>{$('auto-now').checked=false;renderRecord();};$('auto-now').onchange=()=>{if($('auto-now').checked)$('datetime').value=C.localInput();renderRecord();};
$('pokemon-search').oninput=()=>{selected='';$('add-pokemon').disabled=true;$('selected-name').textContent='一覧から選んでください。';renderCatalog();};
$('add-pokemon').onclick=()=>{if(!names.includes(selected))return;const p={id:uid(),species:selected,nickname:$('nickname').value.trim(),profile:null};if(commit({...state,pokemon:[...state.pokemon,p]},label(p)+'を登録しました。')){$('nickname').value='';if(['ミュウ','デリバード'].includes(p.species)){showTab('settings');$('profile-select').value=p.id;editProfile();notice('続けて個体情報を設定してください。');}}};
for(const id of ['period','summary-date','summary-actor','candy-month','analysis-level','analysis-multiplier','analysis-amount','analysis-actor'])$(id).onchange=renderSummary;
$('analysis-method').onchange=()=>{$('analysis-actor').value='';renderActorFilters();renderSummary();};for(let i=1;i<=8;i++)$('analysis-level').add(new Option(String(i),String(i)));
for(const method of ['mew','delibird'])$('enable-'+method).onchange=()=>commit({...state,settings:{...state.settings,[method]:$('enable-'+method).checked}},'表示設定を保存しました。');
optionList($('profile-nature'),natures.map(n=>({id:n,text:n})),'');for(let i=0;i<5;i++){const l=el('label',`サブスキル · Lv.${[10,25,50,75,100][i]}`),s=el('select');s.id='subskill-'+i;optionList(s,subskills.map(n=>({id:n,text:n})),'','未入力');l.append(s);$('subskill-fields').append(l);}
$('profile-select').onchange=editProfile;
$('profile-form').onsubmit=e=>{e.preventDefault();const p=state.pokemon.find(p=>p.id===$('profile-select').value);if(!p)return;const profile={level:Number($('profile-level').value),nature:p.species==='ミュウ'?'きまぐれ':$('profile-nature').value,skillLevel:Number($('profile-skill').value),subskills:Array.from({length:5},(_,i)=>$('subskill-'+i).value)};if(!C.profileValid(profile,p.species)){notice('個体情報の値と、サブスキルの重複を確認してください。');return;}commit({...state,pokemon:state.pokemon.map(x=>x.id===p.id?{...p,nickname:$('profile-nickname').value.trim(),profile}:x)},'個体情報を保存しました。過去の履歴は変更していません。');};
$('event-month').onchange=renderEvents;$('cancel-event').onclick=()=>selectEvent(null);
$('event-form').onsubmit=e=>{e.preventDefault();const event={id:eventId||uid(),name:$('event-name').value.trim(),start:$('event-start').value,end:$('event-end').value,target:$('event-target').value,multiplier:Number($('event-multiplier').value),boost:Number($('event-boost').value)};if(commit({...state,events:[...state.events.filter(e=>e.id!==event.id),event]},'イベント補正を保存しました。過去の履歴は変更していません。'))selectEvent(null);};
$('export').onclick=()=>{try{const data=blocked?localStorage.getItem(KEY):JSON.stringify(state,null,2);const url=URL.createObjectURL(new Blob([data||'null'],{type:'application/json'}));const a=el('a');a.href=url;a.download='pokesleep-candy-'+C.gameDay(new Date())+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){notice('バックアップを書き出せませんでした。');}};
$('import').onchange=async()=>{const file=$('import').files[0];if(!file)return;try{const next=C.migrate(JSON.parse(await file.text()),candyMap);if(confirm(`登録${next.pokemon.length}匹・履歴${next.records.length}件で現在のデータを置き換えますか？`)){localStorage.setItem(KEY+'-before-import',localStorage.getItem(KEY)||'null');const wasBlocked=blocked;blocked=false;if(!commit(next,'バックアップを復元しました。'))blocked=wasBlocked;}}catch(e){notice('復元できませんでした：'+e.message);}$('import').value='';};
window.addEventListener('storage',e=>{if(e.key===KEY){blocked=false;state=fresh();load();render();notice(blocked?'他の画面の保存データを読み込めませんでした。':'他の画面での変更を反映しました。');}});
// 朝4時やイベント期間が切り替わった場合も、開いたままの記録画面を更新します。
let lastDay=C.gameDay(new Date());setInterval(()=>{const day=C.gameDay(new Date());if(day!==lastDay){lastDay=day;renderRecord();renderSummary();}},30000);
$('datetime').value=C.localInput();$('summary-date').value=C.gameDay(new Date());$('candy-month').value=C.gameDay(new Date()).slice(0,7);$('event-month').value=$('candy-month').value;load();selectEvent(null);renderCatalog();render();
