const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../core.js'),B=require('../backup.js');
const app=fs.readFileSync(require.resolve('../app.js'),'utf8'),nodes={};
const parents=new WeakMap();
function el(tag,text,cls){return {tag,text,cls,dataset:{},classList:{contains:c=>(cls||'').split(' ').includes(c)},get textContent(){return (this.text||'')+this.children.map(x=>x.textContent||x.text||'').join('')},children:[],append(...xs){for(const x of xs){const old=parents.get(x);if(old&&old!==this)old.children.splice(old.children.indexOf(x),1);parents.set(x,this);if(this.children.includes(x))this.children.splice(this.children.indexOf(x),1);this.children.push(x)}},replaceChildren(...xs){this.children=xs}};}
function qel(tag,text,cls){const n=el(tag,undefined,cls),m=String(text).match(/^(\d+)個$/);if(m){n.append(el('span',Number(m[1]).toLocaleString('ja-JP'),'quantity-number'),el('span','個','quantity-unit'))}else n.text=text;return n}
const $=id=>nodes[id]??=el('div');$('history-period').value='day';
const oldTarget={id:'p',species:'プクリン',nickname:'ぷっくり'},actor={id:'m',species:'ミュウ',nickname:'わたあめ',profile:{skillLevel:8,level:1,nature:'きまぐれ',subskills:[]}};
const state={version:2,pokemon:[{...oldTarget,nickname:'現在の名前'}],team:[null,null,'p',null,null],records:[{id:'r',method:'mew',amount:1,candy:'プリンのアメ',pokemonId:'p',species:'プクリン',slot:3,datetime:'2026-10-07T10:27:00Z',recordedSkillLevel:8,mainSkillId:'energy_s',context:{actor,actorSlot:1,actorId:'m',effectiveLevel:8,event:{multiplier:1,boost:0,name:'通常'},team:[actor,null,oldTarget,null,null]}},{id:'legacy',method:'help',amount:2,candy:'ピカチュウのアメ',species:'ピカチュウ',pokemon:'ピカチュウ',slot:2,datetime:'2026-10-07T10:20:00Z'}],shardRecords:[],events:[],settings:{mew:true,delibird:true}};
const before=JSON.stringify(state),ctx={state,$,el,qel,methods:{mew:'ミュウ',help:'アメ拾い'},C,DateUI:{datetime:()=> '2026/10/07(水) 19:27'},PeriodPicker:{sync(){}},historyRange:()=>null,visibleRecord:()=>true,actorOf:c=>c?.actor,actorPosition:()=> '1R',position:n=>String(n),label:p=>p.species+(p.nickname?'（'+p.nickname+'）':''),mainSkillText:()=> 'オールマイティー（エナジーチャージS）',SK:{forPokemon:()=> 'energy_s',id:v=>v,name:v=>v},speciesEnabled:()=>true,special:()=>true,profileText:()=> '記録時の個体情報',ShardUI:{appendHistory(){}},button:(text,click)=>Object.assign(el('button',text),{onclick:click}),openHistoryEditor:r=>{ctx.edited=r.id},confirm:()=>false,commit:next=>{ctx.next=next}};
vm.createContext(ctx);vm.runInContext(app.slice(app.indexOf('function historicalPokemon('),app.indexOf('function movePokemon(')),ctx);
const tools=fs.readFileSync(require.resolve('../history-tools.js'),'utf8');vm.runInContext(tools.slice(tools.indexOf(' function appendHistory('),tools.indexOf(' function openEditor('))+';this.MewUI={appendHistory}',ctx);
vm.runInContext('renderHistory()',ctx);const card=$('history-list').children[0];assert.equal(card.children[0].children[1].text,'ミュウ');assert.equal(card.children[1].children[1].textContent,'1個');assert.equal(card.children[1].children[0].text,'プリンのアメ');assert.equal(card.children[2].text,'3番　プクリン（ぷっくり）');assert.equal(card.children[0].children[0].text,'19:27');assert(card.children.at(-1).children[0].children.some(x=>x.text==='スキルLv.8'));assert.equal(card.children.at(-1).children[0].children[0].text,'詳細');
assert.equal(card.children.filter(x=>x.text?.includes('ミュウ（わたあめ）')).length,0,'actor name stays in details rather than repeated supplement');
const actions=card.children.at(-1).children[1].children;actions[0].onclick();assert.equal(ctx.edited,'r');actions[1].onclick();assert.equal(ctx.next,undefined,'cancelled delete does not commit');ctx.confirm=()=>true;actions[1].onclick();assert(!ctx.next.records.some(r=>r.id==='r'));ctx.confirm=()=>false;
for(const mode of ['week','month','all']){$('history-period').value=mode;assert.equal(vm.runInContext("historyTime(state.records[0].datetime)",ctx),'10/07(水) 19:27')}
assert.equal(JSON.stringify(state),before);assert.deepEqual(B.read(B.encode(state)),state);
ctx.historyPlace=n=>n+'番';ctx.historyCard=vm.runInContext('historyCard',ctx);ctx.finishHistoryCard=vm.runInContext('finishHistoryCard',ctx);ctx.historicalPokemon=vm.runInContext('historicalPokemon',ctx);ctx.summaryTitle=()=>'';vm.runInContext(fs.readFileSync(require.resolve('../shards.js'),'utf8'),ctx);
state.shardRecords=[{id:'research',method:'research',amount:8000,baseAmount:7000,researchExp:1000,researchLevel:65,targetDate:'2026-10-06',datetime:'2026-10-07T06:00:00Z'},{id:'skill',method:'skill',amount:48741,slot:3,pokemonSnapshot:oldTarget,skillLevel:6,datetime:'2026-10-07T06:00:00Z'}];
const shardBefore=JSON.stringify(state);$('history-list').replaceChildren();vm.runInContext("ShardUI.appendHistory($('history-list'),null)",ctx);assert.equal($('history-list').children[0].children[0].children[1].text,'睡眠リサーチ');assert($('history-list').children[0].children.at(-1).children[0].children.some(n=>n.text==='リサーチレベル 65'));assert.equal($('history-list').children[1].children[2].text,'3番　プクリン（ぷっくり）');assert.equal(JSON.stringify(state),shardBefore);ctx.ShardEditor={open:r=>{ctx.shardEdited=r.id}};const shardActions=$('history-list').children[1].children.at(-1).children[1].children;shardActions[0].onclick();assert.equal(ctx.shardEdited,'skill');ctx.next=undefined;shardActions[1].onclick();assert.equal(ctx.next,undefined);ctx.confirm=()=>true;shardActions[1].onclick();assert(!ctx.next.shardRecords.some(r=>r.id==='skill'));assert.equal(JSON.stringify(state),shardBefore);
console.log('PASS: source/amount hierarchy, recorded candy and individual snapshot, old events, four time modes, compact Mew supplement, research details, edit/cancel-delete delegation, immutable data and CSV');
if(process.argv[2]){
 const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
 const html=n=>'<'+n.tag+(n.cls?' class="'+esc(n.cls)+'"':'')+'>'+esc(n.text)+n.children.map(html).join('')+'</'+n.tag+'>';
 fs.writeFileSync(process.argv[2],'<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="app-design.css"><main class="app"><section id="history"><h2>テスト履歴の表示確認</h2><div id="history-list">'+[card,...$('history-list').children].map(html).join('')+'</div></section></main></html>');
}
