const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const D=require('../dream-clusters.js'),C=require('../core.js'),B=require('../backup.js');
// 現行公開交換表から独立した期待値。旧ランク1=139の表を混ぜない。
for(const [rank,S,M,L] of [[1,578,3468,14450],[50,2393,14358,59825],[65,3506,21036,87650],[70,4018,24108,100450]]){
 for(const [size,unit] of Object.entries({S,M,L})){assert.equal(D.amount(size,1,rank),unit);assert.equal(D.amount(size,3,rank),unit*3);}
}
assert.equal(D.small.length,70);for(const args of [['S',0,70],['S',1.5,70],['XL',1,70],['L',100000,70],['S',1,null],['S',1,71]])assert.throws(()=>D.amount(...args));
const nodes={},make=(tag,text='',cls='')=>{const n={tag,text,cls,children:[],value:'',checked:false,hidden:false,open:false,style:{},dataset:{},classList:{add(){},remove(){}},append(...xs){this.children.push(...xs)},replaceChildren(...xs){this.children=xs},setAttribute(){},querySelectorAll(){return []},closest(){return this},showModal(){this.open=true},close(){this.open=false},add(o){this.children.push(o)},reset(){}};Object.defineProperty(n,'value',{get(){return this._value??''},set(v){this._value=String(v)}});Object.defineProperty(n,'id',{set(v){this._id=v;nodes[v]=this},get(){return this._id}});return n;};
const $=id=>nodes[id]??=make('div');
const initial={version:2,pokemon:[],team:[null,null,null,null,null],records:[],shardRecords:[{id:'legacy',datetime:'2026-10-08T06:00:00+09:00',method:'other',memo:'以前の報酬',amount:123}],events:[],settings:{mew:true,delibird:true}};
const ctx={DreamClusters:D,C,state:structuredClone(initial),$,el:make,button:(text,onclick)=>Object.assign(make('button',text),{onclick}),document:{createTextNode:text=>make('text',text),querySelector:()=>make('main')},Option:function(text,value){return {text,value}},DateUI:{update(){}},notice:text=>{ctx.message=text},uid:(()=>{let id=0;return()=>String(++id)})(),recordDate:()=>new Date('2026-10-10T12:00:00+09:00'),SummaryExtras:{shardSources:[['research','睡眠リサーチ'],['skill','スキル'],['cluster','ゆめのかたまり'],['other','その他']],shardVisible:()=>true},label:p=>p?.species||'',showTab(){},PeriodPicker:{sync(){}},RangePicker:{get:()=>null}};
ctx.commit=next=>{ctx.state=C.migrate(structuredClone(next),{});return true};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../shards.js'),'utf8'),ctx);vm.runInContext('ShardUI.init()',ctx);
const submit=id=>$(id).onsubmit({preventDefault(){}});
$('cluster-size').value='S';$('cluster-count').value='2';$('cluster-size').oninput();assert.equal($('cluster-amount').value,'');submit('shard-cluster-form');assert.equal(ctx.state.shardRecords.length,1);assert(ctx.message.includes('リサーチランク'));
$('research-rank-setting').value='70';submit('research-rank-form');assert.equal(ctx.state.settings.researchRank,70);$('shard-research-date').oninput();assert.equal($('shard-research-level').value,'70');
for(const size of ['S','M','L']){$('cluster-size').value=size;$('cluster-size').oninput();assert.equal($('cluster-amount').value,D.amount(size,2,70).toLocaleString('ja-JP')+'個');submit('shard-cluster-form');}
const clusters=ctx.state.shardRecords.filter(r=>r.method==='cluster');assert.equal(new Set(clusters.map(r=>r.id)).size,3);assert(clusters.every(r=>r.researchRank===70&&r.usedCount===2));
for(const [kind,amount] of [['mission',1000],['achievement',2000],['gift',3000]]){$('shard-other-kind').value=kind;$('shard-other-amount').value=String(amount);$('shard-other-memo').value='補足';submit('shard-other-form');}
assert.equal(D.otherKind(ctx.state.shardRecords[0]),'unclassified');assert.deepEqual(ctx.state.shardRecords[0],initial.shardRecords[0]);
$('shard-research-date').value='2026-10-09';$('shard-research-date').oninput();$('shard-research-exp').value='500';$('shard-research-base').value='1000';submit('shard-research-form');
const research=ctx.state.shardRecords.at(-1);assert.equal(research.amount,1500);assert.equal(research.researchRank,70);assert.equal(research.researchLevel,70);
const before=JSON.stringify(ctx.state.shardRecords);$('research-rank-setting').value='69';submit('research-rank-form');$('shard-research-date').oninput();assert.equal($('shard-research-level').value,'70','existing day displays saved rank');assert.equal(JSON.stringify(ctx.state.shardRecords),before,'setting alone does not alter history');
$('shard-research-date').value='2026-10-10';$('shard-research-date').oninput();assert.equal($('shard-research-level').value,'69');$('shard-research-exp').value='500';$('shard-research-base').value='1000';submit('shard-research-form');assert.equal(ctx.state.shardRecords.at(-1).amount,1000);
// 訂正は記録時ランクを初期値にして、現在設定から再計算しない。
const tools=fs.readFileSync(require.resolve('../history-tools.js'),'utf8');vm.runInContext(tools.slice(tools.indexOf('const ShardEditor='),tools.indexOf('// 全画面の選択肢')),ctx);
ctx.fixture=clusters[2];vm.runInContext('ShardEditor.open(fixture)',ctx);assert.equal($('shard-edit-rank').value,'70');$('shard-edit-count').value='3';$('shard-edit-count').oninput();assert.equal($('shard-edit-amount').value,'301350');const editor=$('shard-editor').children[0];editor.onsubmit({preventDefault(){}});assert.equal(ctx.state.shardRecords.find(r=>r.id===clusters[2].id).amount,301350);assert.equal(ctx.state.shardRecords.find(r=>r.id===clusters[2].id).researchRank,70);
ctx.fixture=ctx.state.shardRecords[0];vm.runInContext('ShardEditor.open(fixture)',ctx);assert.equal($('shard-edit-kind').value,'unclassified');$('shard-edit-amount').value='456';$('shard-editor').children[0].onsubmit({preventDefault(){}});assert.equal(ctx.state.shardRecords[0].memo,'以前の報酬');assert.equal(ctx.state.shardRecords[0].otherKind,'unclassified');
assert.deepEqual(B.read(B.encode(ctx.state)),ctx.state);assert.deepEqual(C.migrate(B.read(B.encode(ctx.state)),{}),ctx.state);assert.deepEqual(C.migrate(B.read(B.encode(initial)),{}).shardRecords,initial.shardRecords);
ctx.state={...ctx.state,settings:{...ctx.state.settings,showShardCluster:false}};const exactTotal=C.sum(ctx.state.shardRecords);assert.equal(C.sum(C.migrate(ctx.state,{}).shardRecords),exactTotal);const removed=ctx.state.shardRecords[1];ctx.commit({...ctx.state,shardRecords:ctx.state.shardRecords.filter(r=>r.id!==removed.id)});assert.equal(C.sum(ctx.state.shardRecords),exactTotal-removed.amount);assert.deepEqual(B.read(B.encode(ctx.state)),ctx.state);
console.log('PASS: verified current S/M/L rates, invalid input/unset rank, shared rank and recorded snapshot, sleep EXP rule at69/70, other categories/legacy unclassified, editing by historical rank, delete, visibility preserves totals, old/new CSV restoration');
