const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),B=require('../backup.js');
const nodes={},listeners={},make=(tag,text,cls)=>({tag,text,cls,children:[],attributes:{},value:'',style:{},append(...x){this.children.push(...x)},replaceChildren(...x){this.children=x},setAttribute(k,v){this.attributes[k]=v},addEventListener(k,v){listeners[k]=v},focus(){this.focused=true},showModal(){this.open=true},close(){this.open=false;listeners.close()}}),$=id=>nodes[id]??=make('div');
const a={id:'a',species:'ミュウ',nickname:'わたあめ'},b={id:'b',species:'ピカチュウ',nickname:'夢花'},c={id:'c',species:'ピカチュウ',nickname:'生姜黒糖'};
const state={version:2,pokemon:[a,b,c],team:['a','b',null,null,null],records:[{id:'old'}],shardRecords:[],events:[],settings:{mew:true,delibird:true}};
const normalize=s=>s.normalize('NFKC').trim().replace(/[\u3041-\u3096]/g,c=>String.fromCharCode(c.charCodeAt(0)+96));
let writes=0,fail=false;const ctx={state,$,el:make,button:(text,onclick,cls)=>Object.assign(make('button',text,cls),{onclick}),label:p=>p.species+'（'+p.nickname+'）',orderedPokemon:()=>state.pokemon,normalize,C:{speciesName:s=>s},document:{body:{style:{position:'',top:'',width:'',overflow:''}}},window:{scrollY:123,scrollTo:o=>{ctx.scrolled=o.top}},commit:next=>{if(fail)return false;writes++;Object.assign(state,next);return true}};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../team-picker.js'),'utf8'),ctx);vm.runInContext('TeamPicker.init();TeamPicker.open(0)',ctx);
assert.equal(ctx.document.body.style.position,'fixed');assert.equal($('team-picker-close').focused,true);
const rows=()=>$('team-picker-list').children,find=text=>rows().find(n=>n.children[0]?.text===text);
assert.equal(find('ミュウ（わたあめ）').attributes['aria-pressed'],'true');assert.equal(find('ピカチュウ（夢花）').disabled,true);assert.equal(find('ピカチュウ（夢花）').children[1].text,'編成中');assert.equal(find('ピカチュウ（生姜黒糖）').disabled,false,'same species distinct ID selectable');
for(const [q,n] of [['みゅ',1],['ミュ',1],['わたあめ',1],['ピカ',2],['ぴか',2],['夢花',1],['該当なし',0]]){$('team-picker-search').value=q;$('team-picker-search').oninput();assert.equal(rows().filter(n=>n.tag==='button').length,n)}
$('team-picker-search').value='わたあめ';$('team-picker-search').oninput();find('ミュウ（わたあめ）').onclick();assert.equal(writes,0);assert.equal(ctx.document.body.style.position,'');assert.equal(ctx.scrolled,123);
vm.runInContext('TeamPicker.open(2)',ctx);const before=JSON.stringify({...state,team:null});find('ピカチュウ（夢花）').onclick();assert.equal(writes,0,'used ID also protected at action time');fail=true;find('ピカチュウ（生姜黒糖）').onclick();assert.equal(state.team[2],null);assert.equal($('team-picker').open,true);assert($('team-picker-error').textContent.includes('保存できません'));
fail=false;find('ピカチュウ（生姜黒糖）').onclick();assert.equal(state.team[2],'c');assert.equal($('team-picker').open,false);assert.equal(writes,1);assert.equal(JSON.stringify({...state,team:null}),before);assert.deepEqual(B.read(B.encode(state)),JSON.parse(JSON.stringify(state)));
vm.runInContext('TeamPicker.open(2)',ctx);find('未設定').onclick();assert.equal(state.team[2],null);
vm.runInContext('TeamPicker.open(1)',ctx);$('team-picker-close').onclick();assert.equal(state.team[1],'b');assert.equal($('team-slot-1').focused,true);
console.log('PASS: live kana/name/nickname search, selected/used markers, same-species ID distinction, no-op/cancel, save failure, existing commit, unset, body-scroll/focus restore, unchanged records and CSV');
// 編成保存後に、実際の記録画面描画が新しい個体を参照することを確認。
ctx.methods={help:'アメ拾い'};ctx.ShardUI={renderInputs(){}};ctx.SummaryExtras={recordSummary(){}};ctx.CopySkills={render(){}};ctx.recordVisible=()=>true;ctx.speciesEnabled=()=>true;ctx.currentTeam=()=>state.team.map(id=>state.pokemon.find(p=>p.id===id)||null);ctx.position=n=>String(n);
const app=fs.readFileSync(require.resolve('../app.js'),'utf8');vm.runInContext(app.slice(app.indexOf('function renderRecord()'),app.indexOf('function headingTotal(')),ctx);
ctx.commit=next=>{Object.assign(state,next);vm.runInContext('renderRecord()',ctx);return true};vm.runInContext('TeamPicker.open(2)',ctx);find('ピカチュウ（生姜黒糖）').onclick();assert.equal($('record-methods').children[0].children.find(n=>n.cls==='record-slots').children[2].children[1].text,'ピカチュウ（生姜黒糖）');assert.equal(JSON.stringify({...state,team:null}),before);console.log('PASS: existing save dispatch feeds new team individual into actual record renderer without touching history');
