const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),Backup=require('../backup.js');
const nodes={},node=(tag,text,cls)=>({tag,text,cls,value:'',children:[],dataset:{},append(...xs){this.children.push(...xs)},replaceChildren(...xs){this.children=xs},setAttribute(k,v){this[k]=v},focus(){this.focused=true}}),$=id=>nodes[id]||(nodes[id]=node('div'));
const tabs=['team','roster','register'].map(teamView=>{const n=node('button');n.dataset.teamView=teamView;return n});
const state={version:2,pokemon:[{id:'m',species:'ミュウ',nickname:'わたあめ',profile:{skillLevel:8}},{id:'p',species:'ピカチュウ',nickname:'でんき',profile:null},{id:'l',species:'ルカリオ',nickname:'かけら',profile:{skillLevel:6}}],team:['m','p','l',null,null],records:[{id:'keep',amount:4}],shardRecords:[],events:[],settings:{}};
const ctx={$,state,selected:'',document:{querySelectorAll:()=>tabs},window:{scrollTo(){}},el:node,button:(text,onclick)=>Object.assign(node('button',text),{onclick}),normalize:s=>s.normalize('NFKC').trim().replace(/[\u3041-\u3096]/g,c=>String.fromCharCode(c.charCodeAt(0)+96)),C:{speciesName:s=>s},speciesEnabled:()=>true,orderedPokemon:()=>state.pokemon,special:p=>p.species==='ミュウ',relatedPokemon:p=>p.species!=='ピカチュウ',showOtherPokemon:false,sorting:false,nationalDex:{ミュウ:151,ピカチュウ:25,ルカリオ:448},label:p=>p.species+(p.nickname?'（'+p.nickname+'）':''),mainSkillText:p=>p.species==='ミュウ'?'オールマイティー（ゆびをふる）':'スキル',confirm:()=>false,commit:()=>{throw Error('UIだけの操作で保存してはいけません')},openIndividualEditor:p=>{ctx.opened=p.id;ctx.ui.edit()}};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('../team-ui.js'),'utf8')+';this.ui=TeamUI',ctx);const before=JSON.stringify(state);
ctx.ui.init();assert.equal($('team-panel').hidden,false);assert.equal($('roster-panel').hidden,true);assert.equal($('registration-fields').hidden,true);
tabs[1].onclick();assert.equal($('roster-panel').hidden,false);assert.equal($('individual-editor').hidden,true);assert.equal(tabs[1]['aria-selected'],'true');
ctx.ui.renderRoster();assert.equal($('registered-pokemon-list').children.length,2);
for(const query of ['ぴかちゅう','ピカチュウ','でんき']){$('roster-search').value=query;$('roster-search').oninput();assert.equal($('registered-pokemon-list').children.length,1);assert($('registered-pokemon-list').children[0].children[0].children[0].text.includes('No.025'));}
$('roster-search').value='わた';ctx.ui.renderRoster();const actions=$('registered-pokemon-list').children[0].children[1].children;assert.deepEqual(actions.map(x=>x.text),['編集']);actions[0].onclick();assert.equal(ctx.opened,'m');assert.equal($('roster-panel').hidden,true);assert.equal($('individual-editor').hidden,false);
$('profile-select').value='m';$('profile-remove').onclick();assert.equal(JSON.stringify(state),before);$('profile-back').onclick();assert.equal($('individual-editor').hidden,true);assert.equal($('roster-panel').hidden,false);
tabs[2].onclick();assert.equal($('register-panel').hidden,false);ctx.selected='ミュウ';ctx.ui.registration();assert.equal($('registration-fields').hidden,false);ctx.selected='';ctx.ui.registration();assert.equal($('registration-fields').hidden,true);
let prevented=false;tabs[2].onkeydown({key:'ArrowRight',preventDefault(){prevented=true}});assert(prevented);assert.equal($('team-panel').hidden,false);assert(tabs[0].focused);
assert.equal(JSON.stringify(state),before);assert.deepEqual(Backup.read(Backup.encode(state)),state);
const app=fs.readFileSync(require.resolve('../app.js'),'utf8');Object.assign(ctx,{names:['ピカチュウ'],SkillUI:{registration(){}}});vm.runInContext(app.slice(app.indexOf('function renderCatalog('),app.indexOf('const natures=')),ctx);
$('pokemon-search').value='';vm.runInContext('renderCatalog()',ctx);assert.equal($('pokemon-search-results').hidden,true);assert.equal($('pokemon-search-results').children.length,0);
$('pokemon-search').value='ぴか';vm.runInContext('renderCatalog()',ctx);assert.equal($('pokemon-search-results').children.length,1);$('pokemon-search-results').children[0].onclick();assert.equal(ctx.selected,'ピカチュウ');assert.equal($('registration-fields').hidden,false);
console.log('PASS: initial team, three views, kana/nickname search including ordinary pokemon, edit/back, remove confirmation cancellation, selected-only registration, empty catalog, keyboard navigation, immutable state, CSV roundtrip');
